### PR TITLE
Update act.informative.c

### PR DESCRIPTION
**Pull request by tjr1974**
IN FUNCTION:
look_at_room()

Missing bracket issues prevented display of the room description Fixes bracket issues. 
Room description now displays.

### CODE REVIEW

**Review by Vatiken — COMMENTED** [review]
This looks like a good catch.

While it's not required for functionality, I would also aim for consistent formatting.

And in my personal opinion, we could probably do with a few less {}.

**Comment by welcor** [comment]
Can you indent this so it looks right? the "else" looks off now.

**Comment by tjr1974** [comment]
@ welcor 
indentation fixed.

@Vatiken
There were two unguarded else clauses in that function, which produced comipiler warnings, if you altered the code within those clauses. To fix that I added brackets for those two else clauses.

As for some of the others, you are right. We probably could eliminate the unnecessary ones.

**Comment by Vatiken** [comment]
### Development Branch
It appears the error in this pull request #115, was created in pull request #110. This is not a criticism of the code quality, **but** the purpose of using git is for a proper workflow which prevents bugs like this from getting into the master code. We should have an **_active development branch_** so contributions can be properly tested before hitting the master.

### @tjr1974 
There is nothing inherently wrong with unguarded **IF/ELSE** clauses, in fact, I would argue they are for more readable than unnecessarily guarding clauses.

---
Both of these work just fine, and will compile with no warnings.  ⏬️⏬️⏬️
👍️
```
if (This == That) 
{
    do_stuff();
} 
else 
{
    do_other_stuff();
} 

// VS

if (This == That)
    do_stuff();
else
    do_other_stuff();
```
---
These will also compile with no warnings.  ⏬️⏬️⏬️
👍️
```
if (1 == 1)
    do_stuff();
else
    do_other_stuff();

if (2 == 2)
    do_stuff();
else
    do_other_stuff();
```
---
This code below will provide a warning though as the improper indentation might lead someone to believe that the second if statement falls under the **else** of the first **if** statement.  ⏬️⏬️⏬️
⚠️⚠️⚠️
```
if (1 == 1)
    do_stuff();
else
    do_other_stuff();

    if (2 == 2)
        do_stuff();
    else
        do_other_stuff();

```

```
example.c:17:1: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
   17 | else
      | ^~~~
example.c:20:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
   20 |     if (2 == 2)
```

---

While I'm sure there are some indentation issues in tbaMUD, if you ensure your formatting is aligned properly you shouldn't see this very often. 

I just compiled a fresh tbamud and we have **_(3)_**:
```
aedit.c: In function ‘aedit_parse’:
aedit.c:558:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  558 |       if (OLC_ACTION(d)->command)
      |       ^~

interpreter.c: In function ‘nanny’:
interpreter.c:1615:7: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
 1615 |     } else
      |       ^~~~

autowiz.c: In function ‘read_file’:
autowiz.c:85:3: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
   85 |   while (get_line(fl, line))
      |   ^~~~~

```

**Comment by Vatiken** [comment]
Currently...
---
```
  if ((!IS_NPC(ch) && !PRF_FLAGGED(ch, PRF_BRIEF)) || ignore_brief ||
    ROOM_FLAGGED(IN_ROOM(ch), ROOM_DEATH))
  {
    if (!IS_NPC(ch) && PRF_FLAGGED(ch, PRF_AUTOMAP) && can_see_map(ch))
      str_and_map(world[target_room].description, ch, target_room);
  }
  else
  {
    send_to_char(ch, "%s", world[IN_ROOM(ch)].description);
  }
```
In my opinion, this is more readable.
---
```
  if ((!IS_NPC(ch) && !PRF_FLAGGED(ch, PRF_BRIEF)) || ignore_brief ||
      ROOM_FLAGGED(IN_ROOM(ch), ROOM_DEATH))
  {
    if (!IS_NPC(ch) && PRF_FLAGGED(ch, PRF_AUTOMAP) && can_see_map(ch))
      str_and_map(world[target_room].description, ch, target_room);
    else
      send_to_char(ch, "%s", world[IN_ROOM(ch)].description);
  }
```

**Comment by tjr1974** [comment]
Wow, thank you for all the information. It is appreciated! You're quite right about readability issues.

I apologize for any trouble that I've caused. While I'm familiar with multiple programming languages, C is not one of them. I first started playing with C about 20 days ago.

While most programming languages are generally rather similar, each has its nuances and idiosyncrasies. C is a bit strange to me. Most other languages I've worked with usually require, or at least good practice for them dictate, brackets for all if/else clauses. Other languages don't use them at all.

Now, I must and shall educate myself on the use of curly brackets in C. I already have some tutorials queued up. In this moment though, looking at your examples, it seems the only important curly brackets are at the beginning and end of each function, not so much within a function.

Please, forgive my ignorance. I'm a rather old man. I started programming back in the early 1980s with BASIC and some assembly languages. I've heard it said, "Anybody, who began learning programming with BASIC, will forever be retarded." That might very well be true. :)

**Comment by Vatiken** [comment]
Well "shots fired" as I also started with BASIC back in the day. :)

No trouble caused. Code is going to be contributed and some of it will contain bugs, doesn't matter the skill level of the coder. I think at bare minimum we need to ensure that the "master" branch here compiles clean, so we should be working within a development branch. Then we can at least give the branch a thorough test before merging it with master.

After BASIC, I moved to C back in the late 90s to work on MUDs when they were in their peak. I work primarily with Python and JS these days (web development) and hadn't touched C for quite some time up until a couple days ago. At this point I'm interested in improving my skills with git and github, and might as well do a refresh on C while I'm here. I'll be around if you have any questions.

Thanks for the contributions!
-J

**Comment by tjr1974** [comment]
Seems we have some things in common. Python is my favorite language, but I don't have occassion to use it much. These days, I work primarily with PHP and JS for web dev. I started with git and github about 20 days ago. So I'm just learning how it all works.

Agreed, we probably should be working within a development branch.

Since you're an old hand with MUD code and offered to help with questions, when you have time, could you look at [](https://www.tbamud.com/forum/2-general/5535-custom-auto-exits-issue-i-must-be-missing-something)?

**Comment by welcor** [comment]
Re: Development Branch

Yes, we need a build environment. I figure I can set us up with a set of github actions one of these days.

**Comment by welcor** [comment]
This was much easier than last time I looked at it. We now have a github build action that runs on pull requests.

**Pull request closed without merging**
